import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  Future<void> _launchWebsite() async {
    final Uri url = Uri.parse('https://dhvanicast.com/privacy-policy');
    if (!await launchUrl(url, mode: LaunchMode.externalApplication)) {
      throw Exception('Could not launch $url');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'Privacy Policy',
          style: TextStyle(fontWeight: FontWeight.bold, color: Colors.white),
        ),
        backgroundColor: const Color(0xFF1a1a1a),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [Color(0xFF1a1a1a), Color(0xFF2a2a2a)],
          ),
        ),
        child: SingleChildScrollView(
          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildHeader(),
              const SizedBox(height: 20),
              _buildContactCard(),
              const SizedBox(height: 24),

              _buildSectionTitle('2.1 Purpose and Scope'),
              _buildParagraph(
                'Dhvani Cast respects the privacy of its users and is committed to protecting personal data shared with or collected through the platform. This Privacy Policy explains how Dhvani Cast collects, uses, stores, processes, and discloses personal data when users access or use the Dhvani Cast mobile application and related services.',
              ),
              const SizedBox(height: 8),
              _buildParagraph(
                'This policy applies to all users and all interactions with the platform, including public and private frequencies, live audio communication, text chat, image sharing, account management, and paid services.',
              ),
              const SizedBox(height: 8),
              _buildParagraph(
                'This Privacy Policy is governed by and compliant with the Digital Personal Data Protection Act, 2023 (India), the Information Technology Act, 2000, and applicable rules and regulations.',
              ),
              const SizedBox(height: 20),

              _buildSectionTitle('2.2 Categories of Personal Data Collected'),
              _buildParagraph(
                'Dhvani Cast collects only such personal data as is reasonably necessary to operate the platform, ensure safety, comply with legal obligations, and improve service quality.',
              ),
              const SizedBox(height: 16),

              _buildSubsectionTitle('2.2.1 Account and Identity Information'),
              _buildBulletPoints([
                'Email address used for account registration',
                'Unique user identifiers generated by the platform',
                'Account status, login timestamps, and verification indicators',
              ]),
              const SizedBox(height: 8),
              _buildParagraph(
                'This data is essential for account creation, authentication, security, and communication.',
              ),
              const SizedBox(height: 16),

              _buildSubsectionTitle('2.2.2 Optional Profile Information'),
              _buildBulletPoints([
                'Display name chosen by the user',
                'Profile image (if uploaded)',
                'User preferences and app settings',
              ]),
              const SizedBox(height: 8),
              _buildParagraph(
                'Providing profile information is optional and remains under user control at all times.',
              ),
              const SizedBox(height: 16),

              _buildSubsectionTitle('2.2.3 Usage and Interaction Data'),
              _buildBulletPoints([
                'Frequency participation details (join/leave times)',
                'Interaction metadata (non-content based)',
                'Feature usage statistics',
              ]),
              const SizedBox(height: 8),
              _buildParagraph(
                'This data helps Dhvani Cast understand platform usage patterns and improve performance, reliability, and user experience.',
              ),
              const SizedBox(height: 16),

              _buildSubsectionTitle('2.2.4 Device and Technical Information'),
              _buildBulletPoints([
                'Device type and operating system',
                'App version and build number',
                'IP address and network information',
              ]),
              const SizedBox(height: 8),
              _buildParagraph(
                'This information is used for security, fraud prevention, compatibility, and diagnostics.',
              ),
              const SizedBox(height: 16),

              _buildSubsectionTitle('2.2.5 Crash Logs and Diagnostic Data'),
              _buildBulletPoints([
                'Error logs',
                'Crash reports',
                'Performance diagnostics',
              ]),
              const SizedBox(height: 8),
              _buildParagraph(
                'Such data is collected solely to identify technical issues, improve application stability, and prevent future failures.',
              ),
              const SizedBox(height: 16),

              _buildSubsectionTitle('2.2.6 Payment-Related Information'),
              _buildBulletPoints([
                'Transaction reference numbers',
                'Payment status and timestamps',
              ]),
              const SizedBox(height: 8),
              _buildParagraph(
                'Dhvani Cast does not collect or store card details, UPI IDs, CVV numbers, or banking credentials. All sensitive payment data is processed directly by Razorpay.',
              ),
              const SizedBox(height: 20),

              _buildSectionTitle(
                '2.3 Live Audio, Chat, and Media Data Handling',
              ),
              _buildParagraph(
                'Dhvani Cast is a real-time communication platform.',
              ),
              const SizedBox(height: 8),
              _buildBulletPoints([
                'Live audio conversations are not recorded by default.',
                'Text chat messages and shared images may be temporarily stored to:\n  • Enable message delivery\n  • Support moderation and abuse prevention\n  • Investigate reported violations\n  • Comply with legal obligations',
              ]),
              const SizedBox(height: 8),
              _buildParagraph(
                'Private frequency data is protected by enhanced access controls and is not publicly searchable.',
              ),
              const SizedBox(height: 20),

              _buildSectionTitle('2.4 Purpose of Data Processing'),
              _buildParagraph(
                'Personal data is processed for the following legitimate purposes:',
              ),
              const SizedBox(height: 8),
              _buildBulletPoints([
                'Account creation and authentication',
                'Enabling live communication features',
                'Ensuring platform safety and abuse prevention',
                'Processing payments and transactions',
                'Providing customer support',
                'Complying with legal and regulatory requirements',
                'Improving platform performance and reliability',
              ]),
              const SizedBox(height: 20),

              _buildSectionTitle('2.5 Payments and Third-Party Processing'),
              _buildParagraph(
                'All payments are processed exclusively through Razorpay, a regulated Indian payment gateway.',
              ),
              const SizedBox(height: 8),
              _buildParagraph('Dhvani Cast:'),
              const SizedBox(height: 8),
              _buildBulletPoints([
                'Does not process payments directly',
                'Does not store sensitive financial data',
                'Receives only confirmation and transaction references',
              ]),
              const SizedBox(height: 8),
              _buildParagraph(
                'Payment processing is governed by Razorpay\'s privacy and security standards.',
              ),
              const SizedBox(height: 20),

              _buildSectionTitle('2.6 Data Security Measures'),
              _buildParagraph(
                'Dhvani Cast implements appropriate technical and organizational safeguards to protect personal data, including:',
              ),
              const SizedBox(height: 8),
              _buildBulletPoints([
                'Encryption of data in transit and at rest',
                'Restricted internal access to personal data',
                'Secure authentication mechanisms',
                'Continuous monitoring for unauthorized access',
              ]),
              const SizedBox(height: 8),
              _buildParagraph(
                'Security practices are reviewed periodically to address evolving risks.',
              ),
              const SizedBox(height: 20),

              _buildSectionTitle('2.7 Data Retention and Deletion'),
              _buildParagraph(
                'Personal data is retained only for as long as necessary to:',
              ),
              const SizedBox(height: 8),
              _buildBulletPoints([
                'Provide the Service',
                'Enforce platform policies',
                'Resolve disputes or investigations',
                'Comply with legal obligations',
              ]),
              const SizedBox(height: 8),
              _buildParagraph(
                'Once data is no longer required, it is securely deleted or anonymized.',
              ),
              const SizedBox(height: 20),

              _buildSectionTitle('2.8 User Rights and Control'),
              _buildParagraph('Users have the right to:'),
              const SizedBox(height: 8),
              _buildBulletPoints([
                'Request access to their personal data',
                'Request correction of inaccurate data',
                'Request deletion of personal data, subject to legal retention requirements',
              ]),
              const SizedBox(height: 8),
              _buildParagraph(
                'Requests may be submitted by emailing support@dhvanicast.com and will be addressed within a reasonable timeframe.',
              ),
              const SizedBox(height: 20),

              _buildSectionTitle('2.9 Data Sharing and Disclosure'),
              _buildParagraph('Dhvani Cast does not sell personal data.'),
              const SizedBox(height: 8),
              _buildParagraph('Data may be shared only:'),
              const SizedBox(height: 8),
              _buildBulletPoints([
                'With trusted service providers (hosting, analytics, payments)',
                'With law enforcement or authorities when legally required',
                'To protect the rights, safety, and integrity of the platform or its users',
              ]),
              const SizedBox(height: 8),
              _buildParagraph(
                'All third parties are bound by confidentiality and data protection obligations.',
              ),
              const SizedBox(height: 20),

              _buildSectionTitle('2.10 Legal Compliance'),
              _buildParagraph('Dhvani Cast complies with:'),
              const SizedBox(height: 8),
              _buildBulletPoints([
                'Digital Personal Data Protection Act, 2023',
                'Information Technology Act, 2000',
                'Applicable IT Rules and regulations',
              ]),
              const SizedBox(height: 20),

              _buildSectionTitle('2.11 Privacy Policy Updates'),
              _buildParagraph(
                'This Privacy Policy may be updated periodically to reflect legal, technical, or operational changes. Material updates will be communicated through the app or email. Continued use of the platform constitutes acceptance of the updated policy.',
              ),
              const SizedBox(height: 32),

              _buildWebsiteButton(context),
              const SizedBox(height: 20),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildHeader() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFF00ff88).withOpacity(0.1),
        borderRadius: BorderRadius.circular(10),
        border: Border.all(
          color: const Color(0xFF00ff88).withOpacity(0.3),
          width: 1,
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          RichText(
            text: const TextSpan(
              style: TextStyle(color: Colors.white70, fontSize: 12),
              children: [
                TextSpan(
                  text: 'Effective Date: ',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(text: '31 December 2025'),
              ],
            ),
          ),
          const SizedBox(height: 4),
          RichText(
            text: const TextSpan(
              style: TextStyle(color: Colors.white70, fontSize: 12),
              children: [
                TextSpan(
                  text: 'Jurisdiction: ',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(text: 'India'),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildContactCard() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFF00ff88).withOpacity(0.1),
        border: Border.all(color: const Color(0xFF00ff88), width: 1.5),
        borderRadius: BorderRadius.circular(10),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Official Contact Emails',
            style: TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.bold,
              color: Color(0xFF00ff88),
            ),
          ),
          const SizedBox(height: 12),
          RichText(
            text: const TextSpan(
              style: TextStyle(color: Colors.white70, fontSize: 13),
              children: [
                TextSpan(
                  text: 'General Support & Enquiries:\n',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                TextSpan(
                  text: 'support@dhvanicast.com',
                  style: TextStyle(
                    color: Color(0xFF00ff88),
                    fontWeight: FontWeight.bold,
                    fontSize: 14,
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 8),
          RichText(
            text: const TextSpan(
              style: TextStyle(color: Colors.white70, fontSize: 13),
              children: [
                TextSpan(
                  text: 'Child Safety & CSAE Reporting:\n',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                TextSpan(
                  text: 'csae@dhvanicast.com',
                  style: TextStyle(
                    color: Color(0xFF00ff88),
                    fontWeight: FontWeight.bold,
                    fontSize: 14,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: const TextStyle(
        fontSize: 18,
        fontWeight: FontWeight.bold,
        color: Colors.white,
      ),
    );
  }

  Widget _buildSubsectionTitle(String title) {
    return Text(
      title,
      style: const TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w600,
        color: Colors.white,
      ),
    );
  }

  Widget _buildParagraph(String text) {
    return Text(
      text,
      style: const TextStyle(fontSize: 14, height: 1.6, color: Colors.white70),
      textAlign: TextAlign.justify,
    );
  }

  Widget _buildBulletPoints(List<String> points) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: points
          .map(
            (point) => Padding(
              padding: const EdgeInsets.only(left: 16, bottom: 6),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text(
                    '• ',
                    style: TextStyle(fontSize: 14, color: Color(0xFF00ff88)),
                  ),
                  Expanded(
                    child: Text(
                      point,
                      style: const TextStyle(
                        fontSize: 14,
                        height: 1.6,
                        color: Colors.white70,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          )
          .toList(),
    );
  }

  Widget _buildWebsiteButton(BuildContext context) {
    return Center(
      child: ElevatedButton.icon(
        onPressed: _launchWebsite,
        icon: const Icon(Icons.open_in_browser),
        label: const Text('View Full Privacy Policy on Website'),
        style: ElevatedButton.styleFrom(
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 14),
          backgroundColor: const Color(0xFF00ff88),
          foregroundColor: Colors.black,
          textStyle: const TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
        ),
      ),
    );
  }
}
