// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCICEY7AlvKzGooYjQAP9cpVG4QxWuT3o',
    appId: '1:285475395710:web:70c7eac4c5365f8674602f',
    messagingSenderId: '285475395710',
    projectId: 'dhvanicast-965b6',
    authDomain: 'dhvanicast-965b6.firebaseapp.com',
    storageBucket: 'dhvanicast-965b6.firebasestorage.app',
    measurementId: 'G-449GEXYK1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4dudDjNVwg85Z9llEyy05ctu1BsreDjg',
    appId: '1:285475395710:android:cca5f649bd9da53f74602f',
    messagingSenderId: '285475395710',
    projectId: 'dhvanicast-965b6',
    storageBucket: 'dhvanicast-965b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAglMhbp53y8Cnd6cQaHLTxDqmYtE7zBM8',
    appId: '1:285475395710:ios:57ae29e97239d1a274602f',
    messagingSenderId: '285475395710',
    projectId: 'dhvanicast-965b6',
    storageBucket: 'dhvanicast-965b6.firebasestorage.app',
    iosBundleId: 'com.example.harborleafRadioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAglMhbp53y8Cnd6cQaHLTxDqmYtE7zBM8',
    appId: '1:285475395710:ios:57ae29e97239d1a274602f',
    messagingSenderId: '285475395710',
    projectId: 'dhvanicast-965b6',
    storageBucket: 'dhvanicast-965b6.firebasestorage.app',
    iosBundleId: 'com.example.harborleafRadioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCICEY7AlvKzGooYjQAP9cpVG4QxWuT3o',
    appId: '1:285475395710:web:cbd276088e2103d574602f',
    messagingSenderId: '285475395710',
    projectId: 'dhvanicast-965b6',
    authDomain: 'dhvanicast-965b6.firebaseapp.com',
    storageBucket: 'dhvanicast-965b6.firebasestorage.app',
    measurementId: 'G-VDJV72L1C2',
  );
}
